# Generated by Django 2.2.2 on 2019-06-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selfcar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('reserv_day', models.CharField(max_length=50)),
                ('reserv_order', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Create Date')),
            ],
        ),
    ]
