# Generated by Django 2.2.2 on 2019-06-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfcar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfcar',
            name='reserv_day',
        ),
        migrations.AlterField(
            model_name='selfcar',
            name='reserv_order',
            field=models.IntegerField(),
        ),
    ]
