# Generated by Django 2.2.2 on 2019-06-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfcar', '0002_auto_20190630_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveSelfcar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('reserv_day', models.IntegerField()),
                ('reserv_time', models.IntegerField()),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Create Date')),
            ],
        ),
        migrations.DeleteModel(
            name='Selfcar',
        ),
    ]
