# Generated by Django 3.2 on 2023-09-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfcar', '0003_auto_20190630_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveselfcar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
